<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>SmintIo.Portals.DataAdapter.Picturepark</RootNamespace>
    <AssemblyName>SmintIo.Portals.DataAdapter.Picturepark</AssemblyName>
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <Version>1.0.0.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\ConfigurationMessages.de.resx" />
    <EmbeddedResource Include="Resources\ConfigurationMessages.resx">
      <LastGenOutput>ConfigurationMessages.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\MetamodelMessages.de.resx" />
    <EmbeddedResource Include="Resources\MetamodelMessages.es.resx" />
    <EmbeddedResource Include="Resources\MetamodelMessages.it.resx" />
    <EmbeddedResource Include="Resources\MetamodelMessages.pt.resx" />
    <EmbeddedResource Include="Resources\MetamodelMessages.resx">
      <LastGenOutput>MetamodelMessages.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\PictureparkExternalUsersConfigurationMessages.de.resx" />
    <EmbeddedResource Include="Resources\PictureparkExternalUsersConfigurationMessages.resx">
      <LastGenOutput>PictureparkExternalUsersConfigurationMessages.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DotLiquid" Version="2.2.692" />
    <PackageReference Include="SmintIo.Portals.DataAdapterSDK" Version="8.6.171" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Connectors\Connector-Picturepark\Connector-Picturepark.csproj">
      <Private>false</Private>
      <ExcludeAssets>runtime</ExcludeAssets>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Resources\ConfigurationMessages.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ConfigurationMessages.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\MetamodelMessages.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MetamodelMessages.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\PictureparkExternalUsersConfigurationMessages.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>PictureparkExternalUsersConfigurationMessages.resx</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>