<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>SmintIo.Portals.DataAdapter.SharePoint</RootNamespace>
    <AssemblyName>SmintIo.Portals.DataAdapter.SharePoint</AssemblyName>
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <Version>1.0.0.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\OneDriveConfigurationMessages.de.resx" />
    <EmbeddedResource Include="Resources\OneDriveConfigurationMessages.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>OneDriveConfigurationMessages.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\SharepointConfigurationMessages.de.resx" />
    <EmbeddedResource Include="Resources\SharepointConfigurationMessages.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>SharepointConfigurationMessages.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="SmintIo.Portals.DataAdapterSDK" Version="8.6.172" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Connectors\Connector-SharePoint\Connector-SharePoint.csproj">
      <Private>false</Private>
      <ExcludeAssets>runtime</ExcludeAssets>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Resources\ConfigurationMessages.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ConfigurationMessages.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\OneDriveConfigurationMessages.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>OneDriveConfigurationMessages.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\SharepointConfigurationMessages.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SharepointConfigurationMessages.resx</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>