<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>SmintIo.Portals.Connector.SharePoint</AssemblyName>
    <RootNamespace>SmintIo.Portals.Connector.SharePoint</RootNamespace>
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <Version>1.0.0.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\OneDriveConfigurationMessages.de.resx" />
    <EmbeddedResource Include="Resources\OneDriveConfigurationMessages.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>OneDriveConfigurationMessages.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\OneDriveMetamodelMessages.de.resx" />
    <EmbeddedResource Include="Resources\OneDriveMetamodelMessages.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>OneDriveMetamodelMessages.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\SharepointConfigurationMessages.de.resx" />
    <EmbeddedResource Include="Resources\SharepointConfigurationMessages.resx">
      <LastGenOutput>SharepointConfigurationMessages.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\SharepointMetamodelMessages.de.resx" />
    <EmbeddedResource Include="Resources\SharepointMetamodelMessages.resx">
      <LastGenOutput>SharepointMetamodelMessages.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Graph" Version="4.25.0" />
    <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="17.9.28">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="SmintIo.Portals.ConnectorSDK" Version="8.6.172" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Resources\OneDriveConfigurationMessages.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>OneDriveConfigurationMessages.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\OneDriveMetamodelMessages.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>OneDriveMetamodelMessages.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\SharepointConfigurationMessages.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SharepointConfigurationMessages.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\SharepointMetamodelMessages.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SharepointMetamodelMessages.resx</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>