<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>SmintIo.Portals.DataAdapter.HelloWorld</RootNamespace>
    <AssemblyName>SmintIo.Portals.DataAdapter.HelloWorld</AssemblyName>
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <Version>1.0.0.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\ConfigurationMessages.de.resx" />
    <EmbeddedResource Include="Resources\ConfigurationMessages.resx">
      <LastGenOutput>ConfigurationMessages.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="SmintIo.Portals.DataAdapterSDK" Version="8.6.172" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Connectors\Connector-HelloWorld\Connector-HelloWorld.csproj">
      <Private>false</Private>
      <ExcludeAssets>runtime</ExcludeAssets>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Resources\ConfigurationMessages.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ConfigurationMessages.resx</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>